apiVersion: v1
kind: Service
metadata:
  annotations:
    io.kompose.network/2026-s7-esiea-devops-cicd-tp1-wordpress-net: "true"
    io.kompose.service: mariadb
    kompose.cmd: kompose convert -f docker-compose.yml -o PaulineSoubrieWordpress/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mariadb
