---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-password
type: Opaque
data:
  mariadb_root_password: amhkaWUhw6g1Njc1NGZ2ZHMvLixraWQr
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-database
type: Opaque
data:
  mariadb_database: d29yZHByZXNzZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-user
type: Opaque
data:
  mariadb_user: cGF1bGluZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-password
type: Opaque
data:
  mariadb_password: amhkaWUhw6g1Njc1NGZ2ZHMvLixraWQr
