apiVersion: v1
kind: Service
metadata:
  annotations:
    io.kompose.network/2026-s7-esiea-devops-cicd-tp1-wordpress-net: "true"
    io.kompose.service: wordpress
    kompose.cmd: kompose convert -f docker-compose.yml -o PaulineSoubrieWordpress/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: wordpress
